// src/pages/MovieForm.tsx
import { useEffect, useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { useForm } from 'react-hook-form';
import toast from 'react-hot-toast';
import { moviesApi, Movie } from '../api/services';

interface Props {
  mode: 'create' | 'edit';
}

type FormData = Omit<Movie, 'id' | 'avg_rating'>;

export default function MovieForm({ mode }: Props) {
  const { id } = useParams();
  const navigate = useNavigate();
  const [submitting, setSubmitting] = useState(false);
  const { register, handleSubmit, reset, formState: { errors } } = useForm<FormData>({
    defaultValues: { media_type: 'movie' },
  });

  useEffect(() => {
    if (mode === 'edit' && id) {
      moviesApi.get(Number(id)).then((m) => reset(m)).catch(() => toast.error('Błąd ładowania'));
    }
  }, [mode, id]);

  const onSubmit = async (data: FormData) => {
    setSubmitting(true);
    const payload = {
      ...data,
      year: Number(data.year),
      duration_minutes: data.duration_minutes ? Number(data.duration_minutes) : null,
    };
    try {
      if (mode === 'create') {
        const created = await moviesApi.create(payload);
        toast.success('Film dodany');
        navigate(`/movies/${created.id}`);
      } else {
        await moviesApi.update(Number(id), payload);
        toast.success('Zapisano zmiany');
        navigate(`/movies/${id}`);
      }
    } catch (err: any) {
      toast.error(err.message || 'Błąd zapisu');
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <div className="form-card">
      <h1>{mode === 'create' ? 'Dodaj film / serial' : 'Edytuj'}</h1>
      <form onSubmit={handleSubmit(onSubmit)} noValidate>
        <div className="field">
          <label>Tytuł *</label>
          <input {...register('title', {
            required: 'Tytuł jest wymagany',
            maxLength: { value: 200, message: 'Maksymalnie 200 znaków' },
          })} />
          {errors.title && <span className="error">{errors.title.message}</span>}
        </div>

        <div className="field-row">
          <div className="field">
            <label>Rok *</label>
            <input type="number" {...register('year', {
              required: 'Rok jest wymagany',
              min: { value: 1888, message: 'Najwcześniej 1888' },
              max: { value: 2100, message: 'Zbyt odległy rok' },
            })} />
            {errors.year && <span className="error">{errors.year.message}</span>}
          </div>

          <div className="field">
            <label>Typ</label>
            <select {...register('media_type')}>
              <option value="movie">Film</option>
              <option value="series">Serial</option>
            </select>
          </div>
        </div>

        <div className="field">
          <label>Reżyser</label>
          <input {...register('director')} />
        </div>

        <div className="field-row">
          <div className="field">
            <label>Gatunek</label>
            <input {...register('genre')} />
          </div>
          <div className="field">
            <label>Czas (min)</label>
            <input type="number" {...register('duration_minutes', {
              min: { value: 1, message: 'Musi być dodatni' },
            })} />
            {errors.duration_minutes && <span className="error">{errors.duration_minutes.message}</span>}
          </div>
        </div>

        <div className="field">
          <label>Kraj</label>
          <input {...register('country')} />
        </div>

        <div className="field">
          <label>Opis</label>
          <textarea rows={4} {...register('description')} />
        </div>

        <div className="form-actions">
          <button type="button" className="btn" onClick={() => navigate(-1)}>Anuluj</button>
          <button type="submit" className="btn btn-primary" disabled={submitting}>
            {submitting ? 'Zapisywanie...' : 'Zapisz'}
          </button>
        </div>
      </form>
    </div>
  );
}

// src/pages/MovieForm.vue
<script setup lang="ts">
import { ref, reactive, onMounted } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { toast } from 'vue3-toastify';
import { moviesApi } from '../api/services';

const props = defineProps<{ mode: 'create' | 'edit' }>();

const route = useRoute();
const router = useRouter();
const id = Number(route.params.id);

const form = reactive({
  title: '',
  year: '' as number | string,
  media_type: 'movie' as 'movie' | 'series',
  director: '',
  genre: '',
  duration_minutes: '' as number | string,
  country: '',
  description: '',
});
const errors = reactive({ title: '', year: '', duration_minutes: '' });
const submitting = ref(false);

onMounted(async () => {
  if (props.mode === 'edit') {
    try {
      const m = await moviesApi.get(id);
      Object.assign(form, {
        title: m.title,
        year: m.year,
        media_type: m.media_type,
        director: m.director ?? '',
        genre: m.genre ?? '',
        duration_minutes: m.duration_minutes ?? '',
        country: m.country ?? '',
        description: m.description ?? '',
      });
    } catch {
      toast.error('Błąd ładowania');
    }
  }
});

function validate(): boolean {
  if (!form.title) errors.title = 'Tytuł jest wymagany';
  else if (form.title.length > 200) errors.title = 'Maksymalnie 200 znaków';
  else errors.title = '';

  const year = Number(form.year);
  if (!form.year) errors.year = 'Rok jest wymagany';
  else if (year < 1888) errors.year = 'Najwcześniej 1888';
  else if (year > 2100) errors.year = 'Zbyt odległy rok';
  else errors.year = '';

  if (form.duration_minutes && Number(form.duration_minutes) < 1)
    errors.duration_minutes = 'Musi być dodatni';
  else errors.duration_minutes = '';

  return !errors.title && !errors.year && !errors.duration_minutes;
}

async function onSubmit() {
  if (!validate()) return;
  submitting.value = true;
  const payload = {
    title: form.title,
    year: Number(form.year),
    media_type: form.media_type,
    director: form.director || null,
    genre: form.genre || null,
    duration_minutes: form.duration_minutes ? Number(form.duration_minutes) : null,
    country: form.country || null,
    description: form.description || null,
  };
  try {
    if (props.mode === 'create') {
      const created = await moviesApi.create(payload);
      toast.success('Film dodany');
      router.push(`/movies/${created.id}`);
    } else {
      await moviesApi.update(id, payload);
      toast.success('Zapisano zmiany');
      router.push(`/movies/${id}`);
    }
  } catch (err: any) {
    toast.error(err.message || 'Błąd zapisu');
  } finally {
    submitting.value = false;
  }
}
</script>

<template>
  <div class="card mx-auto" style="max-width: 560px">
    <div class="card-body">
      <h1 class="h4 mb-3">{{ props.mode === 'create' ? 'Dodaj film / serial' : 'Edytuj' }}</h1>
      <form @submit.prevent="onSubmit" novalidate>
        <div class="mb-3">
          <label class="form-label">Tytuł *</label>
          <input v-model="form.title" class="form-control" :class="{ 'is-invalid': errors.title }" />
          <div class="invalid-feedback">{{ errors.title }}</div>
        </div>

        <div class="row">
          <div class="col mb-3">
            <label class="form-label">Rok *</label>
            <input v-model="form.year" type="number" class="form-control" :class="{ 'is-invalid': errors.year }" />
            <div class="invalid-feedback">{{ errors.year }}</div>
          </div>
          <div class="col mb-3">
            <label class="form-label">Typ</label>
            <select v-model="form.media_type" class="form-select">
              <option value="movie">Film</option>
              <option value="series">Serial</option>
            </select>
          </div>
        </div>

        <div class="mb-3">
          <label class="form-label">Reżyser</label>
          <input v-model="form.director" class="form-control" />
        </div>

        <div class="row">
          <div class="col mb-3">
            <label class="form-label">Gatunek</label>
            <input v-model="form.genre" class="form-control" />
          </div>
          <div class="col mb-3">
            <label class="form-label">Czas (min)</label>
            <input v-model="form.duration_minutes" type="number" class="form-control" :class="{ 'is-invalid': errors.duration_minutes }" />
            <div class="invalid-feedback">{{ errors.duration_minutes }}</div>
          </div>
        </div>

        <div class="mb-3">
          <label class="form-label">Kraj</label>
          <input v-model="form.country" class="form-control" />
        </div>

        <div class="mb-3">
          <label class="form-label">Opis</label>
          <textarea v-model="form.description" class="form-control" rows="4"></textarea>
        </div>

        <div class="d-flex gap-2 justify-content-end">
          <button type="button" class="btn btn-outline-secondary" @click="router.back()">Anuluj</button>
          <button type="submit" class="btn btn-primary" :disabled="submitting">
            {{ submitting ? 'Zapisywanie...' : 'Zapisz' }}
          </button>
        </div>
      </form>
    </div>
  </div>
</template>
