// src/pages/Watchlist.tsx
import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import toast from 'react-hot-toast';
import { watchlistApi, WatchlistItem } from '../api/services';

export default function Watchlist() {
  const [items, setItems] = useState<WatchlistItem[]>([]);
  const [loading, setLoading] = useState(true);

  const fetch = async () => {
    setItems(await watchlistApi.list());
    setLoading(false);
  };

  useEffect(() => { fetch(); }, []);

  const toggle = async (id: number) => {
    await watchlistApi.toggleWatched(id);
    fetch();
  };

  const remove = async (id: number) => {
    await watchlistApi.remove(id);
    toast.success('Usunięto z listy');
    fetch();
  };

  if (loading) return <p className="loader">Ładowanie...</p>;

  return (
    <div>
      <h1>Do obejrzenia</h1>
      {items.length === 0 ? (
        <p className="empty">
          Lista jest pusta. <Link to="/movies">Przeglądaj filmy</Link> i dodawaj je tutaj.
        </p>
      ) : (
        <ul className="watchlist">
          {items.map((item) => (
            <li key={item.id} className={item.watched ? 'watched' : ''}>
              <input
                type="checkbox"
                checked={item.watched}
                onChange={() => toggle(item.id)}
              />
              <Link to={`/movies/${item.movie_id}`} className="watchlist-title">
                {item.movie.title} <span className="muted">({item.movie.year})</span>
              </Link>
              <button onClick={() => remove(item.id)} className="btn btn-sm btn-danger">Usuń</button>
            </li>
          ))}
        </ul>
      )}
    </div>
  );
}

// src/pages/Watchlist.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { toast } from 'vue3-toastify';
import { watchlistApi, type WatchlistItem } from '../api/services';

const items = ref<WatchlistItem[]>([]);
const loading = ref(true);

async function fetchItems() {
  items.value = await watchlistApi.list();
  loading.value = false;
}

onMounted(fetchItems);

async function toggle(id: number) {
  await watchlistApi.toggleWatched(id);
  fetchItems();
}

async function remove(id: number) {
  await watchlistApi.remove(id);
  toast.success('Usunięto z listy');
  fetchItems();
}
</script>

<template>
  <div>
    <h1>Do obejrzenia</h1>

    <p v-if="loading" class="loader">Ładowanie...</p>
    <p v-else-if="items.length === 0" class="empty">
      Lista jest pusta. <RouterLink to="/movies">Przeglądaj filmy</RouterLink> i dodawaj je tutaj.
    </p>

    <ul v-else class="watchlist">
      <li v-for="item in items" :key="item.id" :class="{ watched: item.watched }">
        <input type="checkbox" :checked="item.watched" @change="toggle(item.id)" />
        <RouterLink :to="`/movies/${item.movie_id}`" class="watchlist-title">
          {{ item.movie.title }} <span class="muted">({{ item.movie.year }})</span>
        </RouterLink>
        <button @click="remove(item.id)" class="btn btn-sm btn-danger">Usuń</button>
      </li>
    </ul>
  </div>
</template>
